version: '3'
services:
  webserver:
    build:
      context: ./config/docker
    container_name: webserver-npf
    restart: on-failure
    expose:
      - '9000'
    ports:
      - '80:80'
    volumes:
      - '${DOCUMENT_ROOT-./www}:/var/www/html'
    environment:
      PHP_XDEBUG_ENABLED: 1
      XDEBUG_CONFIG: remote_host=host.docker.internal
      PHP_IDE_CONFIG: serverName=localhost
